apiVersion: v1
kind: ConfigMap
metadata:
  name: custom-collector-config
  namespace: monitoring
data:
  collector-config.yaml: |
    extensions:
      health_check:
        endpoint: 0.0.0.0:13133

    receivers:
      knx:
        connection:
          type: "router"
          multicast_address: "224.0.23.12:3671"
        read_startup_interval: 200ms
        address_configs:
          "1/1/1":
            name: "strom_eg_kueche_wh"
            dpt: "13.010"
            export: true
            metric_type: "sum"
            read_startup: true
            labels:
              room: "kueche"
              floor: "eg"
          "1/1/2":
            name: "leistung_eg_kueche_w"
            dpt: "14.056"
            export: true
            metric_type: "gauge"
            read_startup: true
            labels:
              room: "kueche"
              floor: "eg"

      syr:
        endpoint: "http://192.168.1.100:5333"
        collection_interval: 2m
        timeout: 10s
        metrics:
          FLO:
            enabled: false
          IWH:
            enabled: false
          OWH:
            enabled: false
          VOL:
            enabled: true
          RE1:
            enabled: true
          SS1:
            enabled: true
          SV1:
            enabled: true
          ALA:
            enabled: true
          RG1:
            enabled: true

    exporters:
      prometheusremotewrite:
        endpoint: "http://victoriametrics.monitoring.svc.cluster.local:8428/api/v1/write"
        tls:
          insecure: true

    service:
      extensions: [health_check]
      pipelines:
        metrics:
          receivers: [knx, syr]
          exporters: [prometheusremotewrite]
