apiVersion: v1
kind: Service
metadata:
  name: custom-collector
  namespace: observability
  labels:
    app: custom-collector
spec:
  type: ClusterIP
  selector:
    app: custom-collector
  ports:
    - name: health
      port: 13133
      targetPort: health
      protocol: TCP
