dist:
  name: custom-collector
  description: Custom OpenTelemetry Collector (KNX + SYR NeoSoft 2500 + Fronius Inverter)
  output_path: ./build
  otelcol_version: 0.149.0
  module: github.com/maxarndt/ltw8-otel-custom-collector/collector

receivers:
  - gomod: github.com/maxarndt/ltw8-otel-custom-collector/receiver/knxreceiver v0.0.1
    path: ../receiver/knxreceiver
  - gomod: github.com/maxarndt/ltw8-otel-custom-collector/receiver/syrreceiver v0.0.1
    path: ../receiver/syrreceiver
  - gomod: github.com/maxarndt/ltw8-otel-custom-collector/receiver/froniusreceiver v0.0.1
    path: ../receiver/froniusreceiver

exporters:
  - gomod: go.opentelemetry.io/collector/exporter/debugexporter v0.149.0
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/exporter/prometheusremotewriteexporter v0.149.0

extensions:
  - gomod: github.com/open-telemetry/opentelemetry-collector-contrib/extension/healthcheckextension v0.149.0
