extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  otlp:
    protocols:
      http:
        endpoint: 0.0.0.0:4318

  knx:
    connection:
      type: "tunnel"
      endpoint: "10.8.10.46:3671"
    read_startup_interval: 200ms
    address_configs:
      # consumption
      "30/3/6":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "dachboden"
          floor: "dg"
          outlet: "lueftungsanlage"
      "30/3/7":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "abstellraum"
          floor: "ug"
          outlet: "gefrierschrank"
      "30/3/8":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "heizraum"
          floor: "ug"
          outlet: "heizung"
      "30/3/9":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "kueche"
          floor: "ug"
          outlet: "kuehlschrank"
      "30/3/12":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "technikraum"
          floor: "ug"
          outlet: "netzwerkschrank"
      "30/3/15":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "bad"
          floor: "eg"
          outlet: "handtuchheizkoerper"
      "30/5/5":
        name: "gas_zaehlerstand_l"
        dpt: "12.1200"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "technikflur"
          floor: "ug"
      # weather
      "0/2/0":
        name: "wetter_helligkeit"
        dpt: "9.004"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      "0/2/1":
        name: "wetter_daemmerung"
        dpt: "9.004"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      "0/2/2":
        name: "wetter_temperatur"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      "0/2/3":
        name: "wetter_tag_nacht"
        dpt: "1.002"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      # temperature
      "13/7/0":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "bad"
          floor: "eg"
      "30/1/2":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "bad"
          floor: "ug"
      "30/1/5":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "wohnzimmer"
          floor: "ug"
      "30/1/6":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "esszimmer"
          floor: "ug"
      "30/1/14":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "wohnflur"
          floor: "ug"
      "30/1/16":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "vorratsraum"
          floor: "ug"
      "30/1/18":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "technikflur"
          floor: "ug"
      "30/1/9":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "diele"
          floor: "eg"
      "30/1/10":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "kind1"
          floor: "eg"
      "30/1/13":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "kind2"
          floor: "eg"
      "30/1/20":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "schlafzimmer"
          floor: "eg"
      "30/1/22":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "windfang"
          floor: "eg"
      "30/1/24":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "buero"
          floor: "eg"
      "30/1/29":
        name: "temperatur_soll"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "bad"
          floor: "eg"
      # ventillation
      "30/7/0":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "dach"
          floor: "outdoor"
          kind: "aussenluft"
          device: "HomeVent-ER300"
      "30/7/1":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          kind: "abluft"
          device: "HomeVent-ER300"
      "30/7/2":
        name: "modulation_ist"
        dpt: "5.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          device: "HomeVent-ER300"
      "30/7/15":
        name: "modulation_soll"
        dpt: "5.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          device: "HomeVent-ER300"
      "30/7/3":
        name: "feuchte_ist"
        dpt: "5.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          kind: "abluft"
          device: "HomeVent-ER300"
      "30/7/17":
        name: "feuchte_soll"
        dpt: "5.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          kind: "abluft"
          device: "HomeVent-ER300"
      "30/7/6":
        name: "voc_ist"
        dpt: "5.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          kind: "abluft"
          device: "HomeVent-ER300"
      "30/7/18":
        name: "device_on"
        dpt: "1.002"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          device: "HomeVent-ER300"
      "30/2/14":
        name: "device_on"
        dpt: "1.002"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          device: "Umwelzpumpe-Warmwasser"
          room: "heizraum"
          floor: "ug"

  syr:
    endpoint: "http://10.8.10.170:5333"
    collection_interval: 2m
    timeout: 10s
    metrics:
      FLO:
        enabled: false
      IWH:
        enabled: false
      OWH:
        enabled: false
      VOL:
        enabled: true
      RE1:
        enabled: true
      SS1:
        enabled: true
      SV1:
        enabled: true
      ALA:
        enabled: true
      RG1:
        enabled: true

  fronius:
    endpoint: "http://10.8.10.19"
    collection_interval: 60s
    timeout: 10s
    metrics:
      power_flow: true
      inverter_realtime: true
      meter_realtime: true
      storage_realtime: true
      inverter_info: true
      ohmpilot_realtime: true

exporters:
  prometheusremotewrite:
    endpoint: "http://victoriametrics.observability.svc.cluster.local:8428/api/v1/write"
    resource_to_telemetry_conversion:
      enabled: true
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    metrics:
      # receivers: [otlp, knx, syr, fronius]
      receivers: [otlp, knx, fronius]
      exporters: [prometheusremotewrite]
      # exporters: [debug, prometheusremotewrite]
