extensions:
  health_check:
    endpoint: 0.0.0.0:13133

receivers:
  knx:
    connection:
      type: "tunnel"
      endpoint: "10.8.10.46:3671"
    read_startup_interval: 200ms
    address_configs:
      "30/3/6":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "dachboden"
          floor: "dg"
          outlet: "lueftungsanlage"
      "30/3/7":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "abstellraum"
          floor: "ug"
          outlet: "gefrierschrank"
      "30/3/8":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "heizraum"
          floor: "ug"
          outlet: "heizung"
      "30/3/9":
        name: "elektrische_arbeit_Wh"
        dpt: "13.010"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "kueche"
          floor: "ug"
          outlet: "kuehlschrank"
      "30/5/5":
        name: "gas_zaehlerstand_l"
        dpt: "12.1200"
        export: true
        metric_type: "sum"
        read_startup: true
        labels:
          room: "technikflur"
          floor: "ug"
      "0/2/0":
        name: "wetter_helligkeit"
        dpt: "9.004"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      "0/2/1":
        name: "wetter_daemmerung"
        dpt: "9.004"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      "0/2/2":
        name: "wetter_temperatur"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      "0/2/3":
        name: "wetter_tag_nacht"
        dpt: "1.002"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "gartenhaus"
          floor: "outdoor"
      "30/1/29":
        name: "temperatur_soll"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "bad"
          floor: "eg"
      "13/7/0":
        name: "temperatur_ist"
        dpt: "9.001"
        export: true
        metric_type: "gauge"
        read_startup: true
        labels:
          room: "bad"
          floor: "eg"

  syr:
    endpoint: "http://10.8.10.170:5333"
    collection_interval: 2m
    timeout: 10s
    metrics:
      FLO:
        enabled: false
      IWH:
        enabled: false
      OWH:
        enabled: false
      VOL:
        enabled: true
      RE1:
        enabled: true
      SS1:
        enabled: true
      SV1:
        enabled: true
      ALA:
        enabled: true
      RG1:
        enabled: true

  fronius:
    endpoint: "http://10.8.10.19"
    collection_interval: 60s
    timeout: 10s
    metrics:
      power_flow: true
      inverter_realtime: true
      meter_realtime: true
      storage_realtime: true
      inverter_info: true
      ohmpilot_realtime: true

exporters:
  prometheusremotewrite:
    endpoint: "http://victoriametrics.observability.svc.cluster.local:8428/api/v1/write"
    resource_to_telemetry_conversion:
      enabled: true
    tls:
      insecure: true
  debug:
    verbosity: detailed

service:
  extensions: [health_check]
  pipelines:
    metrics:
      # receivers: [knx, syr, fronius]
      receivers: [knx, fronius]
      exporters: [prometheusremotewrite]
      # exporters: [debug, prometheusremotewrite]
